// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Message struct {
	ID        int64        `json:"id"`
	Message   string       `json:"message"`
	CreatedAt sql.NullTime `json:"created_at"`
}
