// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (message)
VALUES (?)
RETURNING id, message, created_at
`

func (q *Queries) CreateMessage(ctx context.Context, message string) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, message)
	var i Message
	err := row.Scan(&i.ID, &i.Message, &i.CreatedAt)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
`

func (q *Queries) DeleteMessage(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMessage)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, message, created_at FROM messages
LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage)
	var i Message
	err := row.Scan(&i.ID, &i.Message, &i.CreatedAt)
	return i, err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET message = ?
RETURNING id, message, created_at
`

func (q *Queries) UpdateMessage(ctx context.Context, message string) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateMessage, message)
	var i Message
	err := row.Scan(&i.ID, &i.Message, &i.CreatedAt)
	return i, err
}

const upsertMessage = `-- name: UpsertMessage :one
INSERT INTO messages (message)
VALUES (?)
ON CONFLICT DO UPDATE SET
  message = excluded.message,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, message, created_at
`

func (q *Queries) UpsertMessage(ctx context.Context, message string) (Message, error) {
	row := q.db.QueryRowContext(ctx, upsertMessage, message)
	var i Message
	err := row.Scan(&i.ID, &i.Message, &i.CreatedAt)
	return i, err
}
