// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, message string) (Message, error)
	DeleteMessage(ctx context.Context, id int64) error
	GetMessage(ctx context.Context, id int64) (Message, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error)
}

var _ Querier = (*Queries)(nil)
