// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, message string) (Message, error)
	DeleteMessage(ctx context.Context) error
	GetMessage(ctx context.Context) (Message, error)
	UpdateMessage(ctx context.Context, message string) (Message, error)
	UpsertMessage(ctx context.Context, message string) (Message, error)
}

var _ Querier = (*Queries)(nil)
