// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (message)
VALUES (?)
RETURNING id, message, created_at
`

func (q *Queries) CreateMessage(ctx context.Context, message string) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, message)
	var i Message
	err := row.Scan(&i.ID, &i.Message, &i.CreatedAt)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, message, created_at FROM messages
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(&i.ID, &i.Message, &i.CreatedAt)
	return i, err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET message = ?
WHERE id = ?
RETURNING id, message, created_at
`

type UpdateMessageParams struct {
	Message string `json:"message"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateMessage, arg.Message, arg.ID)
	var i Message
	err := row.Scan(&i.ID, &i.Message, &i.CreatedAt)
	return i, err
}

const upsertMessage = `-- name: UpsertMessage :one
INSERT INTO messages (id, message)
VALUES (?, ?)
ON CONFLICT (id) DO UPDATE SET
  message = excluded.message,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, message, created_at
`

type UpsertMessageParams struct {
	ID      int64  `json:"id"`
	Message string `json:"message"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, upsertMessage, arg.ID, arg.Message)
	var i Message
	err := row.Scan(&i.ID, &i.Message, &i.CreatedAt)
	return i, err
}
